version: '3.8'

services:
  ecom:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecom-server
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    restart: unless-stopped